# Generated by Django 4.0.1 on 2022-03-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFormNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('from_name', models.CharField(max_length=50, verbose_name='From Name')),
                ('from_mail', models.EmailField(max_length=50, verbose_name='From Mail')),
                ('to_mail', models.EmailField(max_length=50, verbose_name='To Mail')),
            ],
        ),
        migrations.CreateModel(
            name='NewUserEmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('from_name', models.CharField(max_length=50, verbose_name='From Name')),
                ('from_mail', models.EmailField(max_length=50, verbose_name='From Mail')),
                ('to_mail', models.EmailField(max_length=50, verbose_name='To Mail')),
            ],
        ),
    ]
