# Generated by Django 4.0.1 on 2022-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentformnotification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='newuseremailsetting',
            name='message',
        ),
    ]
