# Generated by Django 4.1.7 on 2023-08-26 14:06

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

	initial = True

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="Category",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("title", models.CharField(max_length=120)),
				(
					"slug",
					models.SlugField(
						blank=True, max_length=120, null=True, unique=True
					),
				),
				("date_created", models.DateTimeField(auto_now_add=True)),
				("last_modified", models.DateTimeField(auto_now=True)),
			],
			options={
				"verbose_name_plural": "categories",
				"ordering": ["-date_created"],
			},
		),
		migrations.CreateModel(
			name="Post",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("title", models.CharField(max_length=120)),
				(
					"slug",
					models.SlugField(
						blank=True, max_length=120, null=True, unique=True
					),
				),
				("overview", models.TextField()),
				("content", ckeditor.fields.RichTextField()),
				(
					"img_thumbnail",
					models.ImageField(
						upload_to=blog.models.upload_image_path,
						verbose_name="Image thumbnail",
					),
				),
				("publish", models.BooleanField(default=True)),
				("last_modified", models.DateTimeField(auto_now=True)),
				("timestamp", models.DateTimeField(auto_now_add=True)),
				(
					"author",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
				("categories", models.ManyToManyField(to="blog.category")),
			],
			options={
				"ordering": ["-timestamp"],
			},
		),
		migrations.CreateModel(
			name="Comment",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				("content", models.TextField()),
				("created_on", models.DateTimeField(auto_now_add=True)),
				(
					"post",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="comments",
						to="blog.post",
					),
				),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				"ordering": ["-created_on"],
			},
		),
	]
