# Generated by Django 3.1.3 on 2020-11-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='is_publish',
        ),
    ]
