# Generated by Django 4.0.1 on 2022-03-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_commentformnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentformnotification',
            name='from_mail',
            field=models.CharField(max_length=50, verbose_name='From Mail'),
        ),
    ]
