# Generated by Django 4.0.1 on 2022-03-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_commentformnotification_from_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentformnotification',
            name='from_name',
            field=models.CharField(default='name', max_length=50, verbose_name='From Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentformnotification',
            name='from_mail',
            field=models.EmailField(max_length=50, verbose_name='From Mail'),
        ),
    ]
