# Generated by Django 4.0.1 on 2022-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_commentformnotification_from_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentFormNotification',
        ),
    ]
