# Generated by Django 3.0.3 on 2020-07-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercredit',
            name='left_credit',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='footercredit',
            name='right_credit',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footer_1',
            field=models.CharField(max_length=120),
        ),
    ]
