# Generated by Django 3.0.3 on 2020-07-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_auto_20200710_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercredit',
            name='name_of_the_settings',
            field=models.CharField(default='Settings 1', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='name_of_the_settings',
            field=models.CharField(default='New', max_length=120),
            preserve_default=False,
        ),
    ]
