# Generated by Django 3.0.3 on 2020-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_auto_20200710_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='footer_1',
            field=models.TextField(),
        ),
    ]
