# Generated by Django 3.0.3 on 2020-07-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_auto_20200710_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footercredit',
            old_name='name_of_the_settings',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='name_of_the_settings',
            new_name='title',
        ),
    ]
