# Generated by Django 4.0.1 on 2022-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newuseremailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuseremailsettings',
            name='to_mail',
            field=models.EmailField(default='evan@webphics.com', max_length=50, verbose_name='To Mail'),
            preserve_default=False,
        ),
    ]
