# Generated by Django 4.0.1 on 2022-03-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_emailsmtpsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSMTPSettings',
        ),
    ]
