# Generated by Django 4.0.1 on 2022-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_emailsmtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=25, verbose_name='Email Host (SMTP connection)')),
                ('email_port', models.PositiveIntegerField(verbose_name='Email PORT')),
                ('email_host_user', models.EmailField(max_length=25, verbose_name='Email Address')),
                ('default_from_email', models.EmailField(max_length=25, verbose_name='Default From Email')),
                ('email_host_password', models.CharField(max_length=100, verbose_name='Email Password')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='Email TLS')),
            ],
        ),
    ]
