# Generated by Django 4.0.1 on 2022-03-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_emailsmtpsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSMTPSettings',
            new_name='EmailSMTPSetting',
        ),
        migrations.RenameModel(
            old_name='NewUserEmailSettings',
            new_name='NewUserEmailSetting',
        ),
    ]
