# Generated by Django 4.0.1 on 2022-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_emailsmtpsettings_emailsmtpsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuseremailsetting',
            name='from_mail',
            field=models.CharField(max_length=50, verbose_name='From Mail'),
        ),
    ]
