# Generated by Django 4.0.1 on 2022-03-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_newuseremailsetting_from_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSMTPSetting',
        ),
    ]
