# Generated by Django 4.0.1 on 2022-03-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_emailsmtpsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUserEmailSetting',
        ),
    ]
