# Generated by Django 4.0.1 on 2022-03-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('site_name', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=5)),
            ],
        ),
    ]
