# Generated by Django 4.0.1 on 2022-06-27 18:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50)),
                ('admin_email', models.EmailField(max_length=50, verbose_name='Admin Email')),
                ('email_address', models.EmailField(max_length=50, verbose_name='Email Address')),
                ('site_name', models.CharField(max_length=20)),
                ('protocol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('plain_text_html', models.TextField(verbose_name='Plain Text HTML')),
                ('message', ckeditor.fields.RichTextField()),
                ('notification_name', models.CharField(choices=[('New User Registration Notification', 'New User Registration Notification'), ('New Comment Notification', 'New Comment Notification'), ('Password Change Notification', 'Password Change Notification')], max_length=256)),
                ('plain_text_html_enable', models.BooleanField(help_text='This will ignore the message field content.', verbose_name='Plain Text HTML Enable')),
            ],
        ),
    ]
