# Generated by Django 4.0.1 on 2022-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsetting',
            name='email_address',
            field=models.EmailField(default='info@webphics.com', max_length=50, verbose_name='Email Address'),
            preserve_default=False,
        ),
    ]
