# Generated by Django 4.0.1 on 2022-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0002_allsetting_email_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_status', models.CharField(choices=[('Password Notification', 'Password Notification')], max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
