# Generated by Django 4.0.1 on 2022-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0003_emailcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcontent',
            name='stock_status',
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('Password Change Notification', 'Password Change Notification')], default='stock', max_length=30),
            preserve_default=False,
        ),
    ]
