# Generated by Django 4.0.1 on 2022-03-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_remove_emailcontent_stock_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allsetting',
            name='admin_email',
            field=models.EmailField(default='note', max_length=50, verbose_name='Admin Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailcontent',
            name='subject',
            field=models.CharField(default='note', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('New User Registration Notification', 'New User Registration Notification'), ('Password Change Notification', 'Password Change Notification')], max_length=256),
        ),
    ]
