# Generated by Django 4.0.1 on 2022-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_allsetting_admin_email_emailcontent_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
