# Generated by Django 4.0.1 on 2022-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0006_alter_emailcontent_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='notification_name',
            field=models.CharField(choices=[('New User Registration Notification', 'New User Registration Notification'), ('New Comment Notification', 'New Comment Notification'), ('Password Change Notification', 'Password Change Notification')], max_length=256),
        ),
    ]
