# Generated by Django 4.0.1 on 2022-03-19 16:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0007_alter_emailcontent_notification_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
