# Generated by Django 4.0.1 on 2022-03-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0008_alter_emailcontent_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='plain_text',
            field=models.TextField(default='note'),
            preserve_default=False,
        ),
    ]
