# Generated by Django 4.0.1 on 2022-03-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0009_emailcontent_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontent',
            name='plain_text_enable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
