# Generated by Django 4.0.1 on 2022-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0010_emailcontent_plain_text_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='plain_text_enable',
            field=models.BooleanField(help_text='This will ignore the message field content.'),
        ),
    ]
