# Generated by Django 4.0.1 on 2022-03-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0011_alter_emailcontent_plain_text_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailcontent',
            old_name='plain_text',
            new_name='plain_text_html',
        ),
        migrations.RenameField(
            model_name='emailcontent',
            old_name='plain_text_enable',
            new_name='plain_text_html_enable',
        ),
    ]
