# Generated by Django 4.0.1 on 2022-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0012_rename_plain_text_emailcontent_plain_text_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcontent',
            name='plain_text_html',
            field=models.TextField(blank=True, null=True, verbose_name='Plain Text HTML'),
        ),
        migrations.AlterField(
            model_name='emailcontent',
            name='plain_text_html_enable',
            field=models.BooleanField(help_text='This will ignore the message field content.', verbose_name='Plain Text HTML Enable'),
        ),
    ]
